% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{caption}
\usepackage{graphicx}
\usepackage{siunitx}
\usepackage{hhline}
\usepackage{calc}
\usepackage{tabularx}
\usepackage{adjustbox}
\usepackage{hyperref}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={BIOS 667 Group 5},
  pdfauthor={Lily Bai; Nathalie Blasco; Yihao Peng; Lauren Rackley; Sirui Wu},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{BIOS 667 Group 5}
\author{Lily Bai \and Nathalie Blasco \and Yihao Peng \and Lauren
Rackley \and Sirui Wu}
\date{2025-11-21}

\begin{document}
\maketitle

\subsection{Introduction}\label{introduction}

The purpose of this project is to examine the effects of botulism toxin
type B (BotB) to treat cervical dystonia over time. Cervical dystonia
(CD) is a chronic neurological disorder, in which patients have painful
involuntary contractions in neck muscles. CD is more prevalent in women
(Jankovic et al., 2023). The prevalence of CD is estimated to be 28-183
cases per million. The data comes from a multicenter randomized clinical
trial for cervical dystonia patients with 9 U.S. sites. Botulism toxin
types A and B are first-line treatments for CD (Wetmore et al., 2025).
The treatment groups included in the study were placebo, 5000 U BotB,
and 10000 U BotB. The response variable is Toronto Western Spasmodic
Torticollis Rating Scale (TWSTRS) total score, which ranges from 0 to 85
and is comprised of disability (0-30), pain (0-20), and severity (0-35)
subscores. Only total score is included in this data.The TWSTRS score
was measured at week 0 (baseline), and 2,4,6,8,12, and 16 weeks after
treatment start. Site is included in the dataset but no further details
about site were included in the available dataset documentation.

\subsection{Methods}\label{methods}

\subsubsection{\texorpdfstring{\emph{Study
Population}}{Study Population}}\label{study-population}

Inclusion and exclusion criteria for the trial were not available.
Duration of CD and age at onset were not known. The study included 109
patients (67 (61\%)) females.The mean age was 56 (12). Median age was 56
years. The mean TWSTRS score at baseline was 46 (10). It was not known
if the patients received prior BotB treatments. Information about the
randomization schedule was not provided.

\subsubsection{\texorpdfstring{\emph{Statistical
Analyses}}{Statistical Analyses}}\label{statistical-analyses}

Number of observations, mean, median, standard deviation (SD), minimum
(min) and maximum (max) were provided for age. Mean and SD were
calculated for TWSTRS score at baseline. Frequencies and percentages
were reported for categorical variables. GLM, GLMM, and GEE models were
fit using TWSTRS total score as the response variable. For GLM, age,
sex, site, week, and treatment were used as covariates with male and
placebo being the reference groups. For the GEE model, week, age,sex,
treatment, and treatment \(\times\) week interaction were included in
the model again with male and placebo being the reference groups.

\newpage

\subsection{Results}\label{results}

\begin{longtable}[t]{lllllllll}
\caption{\label{tab:unnamed-chunk-2}TWSTRS scores for 109 patients with CD at weeks 2, 4, 8, 12, 16}\\
\toprule
\textbf{ID} & \textbf{treat} & \textbf{Age} & \textbf{sex} & \textbf{Week 2} & \textbf{Week 4} & \textbf{Week 8} & \textbf{Week 12} & \textbf{Week 16}\\
\midrule
1 & 2 & 65 & 2 & 30 & 24 & 37 & 39 & 36\\
2 & 3 & 70 & 2 & 26 & 27 & 41 & 65 & 67\\
3 & 2 & 64 & 2 & 20 & 23 & 26 & 35 & 35\\
4 & 1 & 59 & 2 & 61 & 64 & 62 &  & \\
5 & 3 & 76 & 2 & 35 & 48 & 49 & 41 & 51\\
6 & 3 & 59 & 2 & 34 & 43 & 48 & 48 & 51\\
7 & 2 & 72 & 1 & 32 & 32 & 43 & 42 & 46\\
8 & 1 & 40 & 1 & 33 & 21 & 27 & 32 & 38\\
9 & 2 & 52 & 2 & 32 & 34 & 35 & 37 & 36\\
10 & 1 & 47 & 1 & 10 & 31 & 32 & 6 & 14\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{lccccc}
\caption{\label{tab:preliminary tables}Summary of Demographic and Baseline Characteristics}\\
\toprule
\multicolumn{3}{c}{ } & \multicolumn{2}{c}{\textbf{BotB}} & \multicolumn{1}{c}{ } \\
\cmidrule(l{3pt}r{3pt}){4-5}
\textbf{Characteristic} & \makecell[c]{\textbf{Overall}\ \ \\N = 109} & \makecell[c]{\textbf{Placebo}\ \ \\N = 36} & \makecell[c]{\textbf{5000 U}\ \ \\N = 36} & \makecell[c]{\textbf{10000 U}\ \ \\N = 37} & \textbf{p-value}\\
\midrule
Sex &  &  &  &  & 0.0706\\
\hspace{1em}Male & 42 (39\%) & 15 (42\%) & 18 (50\%) & 9 (24\%) & \\
\hspace{1em}Female & 67 (61\%) & 21 (58\%) & 18 (50\%) & 28 (76\%) & \\
Age (years) &  &  &  &  & 0.6198\\
\hspace{1em}N & 109 & 36 & 36 & 37 & \\
\hspace{1em}Mean (SD) & 56 (12) & 54 (12) & 57 (12) & 56 (12) & \\
\hspace{1em}Median & 56 & 56 & 57 & 54 & \\
\hspace{1em}Min, Max & 26, 83 & 26, 79 & 35, 83 & 34, 76 & \\
TWSTRS total score at baseline &  &  &  &  & 0.3307\\
\hspace{1em}Mean (SD) & 46 (10) & 44 (9) & 46 (10) & 47 (10) & \\
\bottomrule
\multicolumn{6}{l}{\rule{0pt}{1em}\textsuperscript{1} BotB = botulinum toxin type B; TWSTRS = Toronto Western Spasmodic Torticollis Rating Scale.}\\
\multicolumn{6}{l}{\rule{0pt}{1em}\textsuperscript{2} Pearson's Chi-squared test; Kruskal-Wallis rank sum test}\\
\end{longtable}

\newpage

\subsubsection{Generalized Linear Model
(GLM)}\label{generalized-linear-model-glm}

A generalized linear model (GLM model) using a Gaussian link was fit
including week, site, treatment, age, and sex as predictors (Table 2).

\begin{longtable}[]{@{}lrrrr@{}}
\caption{GLM Model Summary (Gaussian Link)}\tabularnewline
\toprule\noalign{}
term & estimate & std.error & statistic & p.value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
term & estimate & std.error & statistic & p.value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
(Intercept) & 30.227 & 2.850 & 10.605 & 0.000 \\
week & 0.234 & 0.080 & 2.923 & 0.004 \\
treat5000 U & -0.030 & 1.120 & -0.027 & 0.978 \\
treat10000 U & 0.287 & 1.127 & 0.254 & 0.799 \\
age & 0.072 & 0.039 & 1.854 & 0.064 \\
sexFemale & 1.938 & 1.006 & 1.927 & 0.054 \\
site2 & 13.216 & 1.860 & 7.107 & 0.000 \\
site3 & -2.183 & 1.933 & -1.130 & 0.259 \\
site4 & 4.635 & 2.132 & 2.174 & 0.030 \\
site5 & 7.403 & 2.413 & 3.068 & 0.002 \\
site6 & 9.617 & 1.849 & 5.201 & 0.000 \\
site7 & 1.862 & 1.912 & 0.974 & 0.331 \\
site8 & -2.493 & 1.773 & -1.406 & 0.160 \\
site9 & 10.198 & 2.011 & 5.071 & 0.000 \\
\end{longtable}

The coefficient for week was statistically significant, indicating an
overall linear trend in TWSTRS score over time. There was notable
variation across study sites, with several sites showing significantly
higher TWSTRS scores compared to the reference site, highlighting
site-level differences. However, because the GLM assumes independence of
observations, the repeated measures within individuals violate this
assumption. As a result, the standard errors and p-values may be
underestimated, and inference should be interpreted with caution. This
motivates the subsequent use of correlation-aware models such as GEE and
GLMM.

\subsubsection{GLM Model Diagnostics}\label{glm-model-diagnostics}

Diagnostics were assessed for the GLM model.

\pandocbounded{\includegraphics[keepaspectratio]{BIOS-667-Group-Project_files/figure-latex/unnamed-chunk-6-1.pdf}}

Figure 1 shows the residuals versus the fitted values. The absence of
strong patterns or fanning suggests that the linearity and
homoscedasticity assumptions are reasonably met.

\pandocbounded{\includegraphics[keepaspectratio]{BIOS-667-Group-Project_files/figure-latex/unnamed-chunk-7-1.pdf}}

Figure 2 presents a QQ plot of the residuals, which largely follow the
45 degree reference line with mild deviations in the tails. This
indicates that the normality assumption is approximately satisfied.

\pandocbounded{\includegraphics[keepaspectratio]{BIOS-667-Group-Project_files/figure-latex/unnamed-chunk-8-1.pdf}}

Finally, figure 3 displays Cook's distance for all observations. The
conventional threshold, 4/(n-k-1), where n is the number of observations
and k is the number of predictors, was used to assess the influence of
the observations. Several observations exceeded the threshold and were
considered potentially influential and warranted further investigation.
Therefore, a second GLM was fit, excluding those observations.

\begin{longtable}[]{@{}lrrrr@{}}
\caption{GLM Model Summary (Excluding Influential
Observations)}\tabularnewline
\toprule\noalign{}
term & estimate & std.error & statistic & p.value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
term & estimate & std.error & statistic & p.value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
(Intercept) & 31.836 & 2.571 & 12.384 & 0.000 \\
week & 0.215 & 0.072 & 3.002 & 0.003 \\
treat5000 U & -0.185 & 1.004 & -0.184 & 0.854 \\
treat10000 U & 0.800 & 1.001 & 0.799 & 0.424 \\
age & 0.050 & 0.035 & 1.449 & 0.148 \\
sexFemale & 1.046 & 0.903 & 1.158 & 0.247 \\
site2 & 13.405 & 1.667 & 8.043 & 0.000 \\
site3 & -1.417 & 1.741 & -0.814 & 0.416 \\
site4 & 7.636 & 1.947 & 3.921 & 0.000 \\
site5 & 10.761 & 2.283 & 4.714 & 0.000 \\
site6 & 10.152 & 1.661 & 6.111 & 0.000 \\
site7 & 2.380 & 1.707 & 1.394 & 0.164 \\
site8 & -3.384 & 1.605 & -2.108 & 0.035 \\
site9 & 10.049 & 1.861 & 5.400 & 0.000 \\
\end{longtable}

Excluding influential observations resulted in modest shifts in the
parameter estimates and slightly improved precision. Notably, the effect
of week remained statistically significant and variation across study
sites continued to be pronounced. This underscores that site-level
differences remain important even after removing influential
observation.s

Overall, excluding influential points slightly adjusted the estimates
and improved precision, but the main patterns of association were
consistent with the original GLM. As with the previous model, the GLM
assumptions are not appropriate for longitudinal data with correlated
repeated measures. The following GEE and GLMM analyses address this
limitation by explicitly modeling within-subject correlation and random
effects.

\subsubsection{Generalized Estimating Equation
(GEE)}\label{generalized-estimating-equation-gee}

A GEE model with Gaussian family, identity link, and an exchangeable
correlation structure. The mean model included week, treatment,
treatment-by-week interaction, and baseline age and sex, with Placebo as
the reference treatment group.

\pandocbounded{\includegraphics[keepaspectratio]{BIOS-667-Group-Project_files/figure-latex/unnamed-chunk-11-1.pdf}}

Figure 4 shows Pearson residuals plotted against the fitted TWSTRS
values with points colored by treatment group. The residuals are
centered around zero and do not show a strong funnel shape, supporting
the constant-variance assumption. However, many residuals fall outside
\(\pm2\), indicating wide individual variation in TWSTRS trajectories
and suggesting that the simple Gaussian working model does not fully
capture the variance structure. Even so, because the GEE analysis used
robust standard errors, the uncertainty in the regression coefficients
is driven by the observed variability of the residuals within subjects,
rather than depending on the working variance and correlation.

\pandocbounded{\includegraphics[keepaspectratio]{BIOS-667-Group-Project_files/figure-latex/unnamed-chunk-12-1.pdf}}

Figure 5 shows mean TWSTRS over time by treatment group. All groups show
decreases from baseline through weeks 2--4, suggesting early
improvement, followed by increases after week 4. Around week 10, both
active treatment groups begin to show higher TWSTRS scores than the
placebo group.

\begin{longtable}[]{@{}lrrrr@{}}
\caption{GEE Model Summary}\tabularnewline
\toprule\noalign{}
term & estimate & std.error & statistic & p.value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
term & estimate & std.error & statistic & p.value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
(Intercept) & 38.698 & 4.760 & 66.095 & 0.000 \\
week & 0.097 & 0.114 & 0.731 & 0.392 \\
treat5000 U & -0.810 & 2.758 & 0.086 & 0.769 \\
treat10000 U & -2.738 & 2.372 & 1.333 & 0.248 \\
age & 0.014 & 0.078 & 0.033 & 0.855 \\
sexFemale & 2.494 & 2.117 & 1.388 & 0.239 \\
week:treat5000 U & 0.115 & 0.133 & 0.745 & 0.388 \\
week:treat10000 U & 0.323 & 0.146 & 4.899 & 0.027 \\
\end{longtable}

Table 5 summarizes the GEE estimates for TWSTRS over time by treatment,
adjusted for age and sex. The main effects for treat5000U (−0.810, p =
0.769) and treat10000U (−2.738, p = 0.248) compare baseline TWSTRS at
week 0 with placebo. Both estimates are negative but not statistically
significant, indicating no clear baseline differences in mean TWSTRS
between treatment groups and placebo. The treatment-by-week interaction
terms describe how each treatment's trajectory differs from placebo over
time. For 5000U, the additional slope relative to placebo is small and
not significant (0.115, p = 0.388), suggesting that its average linear
trend over time is similar to placebo. For 10000U, the additional slope
is larger and statistically significant (0.323, p = 0.027), indicating
an average increase in TWSTRS over 16 weeks compared with placebo.
Because higher TWSTRS scores reflect worse symptoms, these results imply
that low-dose regimen behaves similarly to placebo, while the high-dose
regimen is associated with faster worsening over time. Overall, the GEE
model provides a reasonable approach for assessing whether treatment
affects population-average TWSTRS trajectories over time, while
recognizing that the true time course is somewhat non-linear and that
estimated treatment effects are relatively small.

\subsubsection{Generalized Linear Mixed Effects Model
(GLMM)}\label{generalized-linear-mixed-effects-model-glmm}

While the GEE model provides population-averaged estimates, we
implemented a Generalized Linear Mixed Model (GLMM) to model
subject-specific heterogeneity. By including a random intercept, the
GLMM partitions the total variance into between-subject and
within-subject components, allowing us to estimate treatment
trajectories conditional on an individual patient's unique baseline
severity. Additionally, because GLMM uses likelihood-based estimation,
they provide valid inference under the Missing at Random (MAR)
assumption.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0787}}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.2022}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1011}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1124}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1124}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0899}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0899}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1011}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1124}}@{}}
\caption{GLMM Model Summary}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
effect
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
term
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
std.error
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
statistic
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
df
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p.value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
conf.low
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
conf.high
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
effect
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
term
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
std.error
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
statistic
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
df
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p.value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
conf.low
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
conf.high
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
fixed & (Intercept) & 38.698 & 5.248 & 7.373 & 107.898 & 0.000 & 28.295
& 49.101 \\
fixed & treat5000 U & -0.810 & 2.748 & -0.295 & 128.543 & 0.769 & -6.246
& 4.627 \\
fixed & treat10000 U & -2.738 & 2.738 & -1.000 & 128.049 & 0.319 &
-8.155 & 2.679 \\
fixed & week & 0.097 & 0.089 & 1.089 & 522.247 & 0.277 & -0.078 &
0.273 \\
fixed & age & 0.014 & 0.088 & 0.162 & 104.208 & 0.871 & -0.159 &
0.188 \\
fixed & sexFemale & 2.495 & 2.216 & 1.126 & 104.884 & 0.263 & -1.898 &
6.888 \\
fixed & treat5000 U:week & 0.115 & 0.125 & 0.916 & 521.089 & 0.360 &
-0.132 & 0.361 \\
fixed & treat10000 U:week & 0.323 & 0.125 & 2.582 & 521.609 & 0.010 &
0.077 & 0.569 \\
\end{longtable}

Table 6 presents the fixed effect estimates from the linear mixed model.
Consistent with the previous GEE analysis, the point estimates for the
fixed effects are identical, as expected for a linear model with a
Gaussian distribution. However, the standard errors and p-values differ
slightly reflecting the distinction between model-based (GLMM) and
robust (GEE) variance estimation.

At baseline, there were no statistically significant differences in
disease severity between the treatment arms and the placebo group.
Neither age nor sex are significant predictors for TWSTRS. The primary
finding is the significant interaction between the 10000 U treatment and
week (\(\beta = 0.323, SE = 0.125, p = 0.010\)). This confirms that,
conditional on the individual patient, the high-dose group experienced a
significantly faster rate of worsening, increasing by approximately 0.32
points per week relative to the placebo group.

 
  \providecommand{\huxb}[2]{\arrayrulecolor[RGB]{#1}\global\arrayrulewidth=#2pt}
  \providecommand{\huxvb}[2]{\color[RGB]{#1}\vrule width #2pt}
  \providecommand{\huxtpad}[1]{\rule{0pt}{#1}}
  \providecommand{\huxbpad}[1]{\rule[-#1]{0pt}{#1}}

\begin{table}[ht]
\begin{centerbox}
\begin{threeparttable}
 \setlength{\tabcolsep}{0pt}
\begin{tabular}{l l l l l l l l}


\hhline{>{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0.4}}r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} \textbf{npar} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} \textbf{AIC} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} \textbf{BIC} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} \textbf{logLik} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} \textbf{-2*log(L)} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} \textbf{Chisq} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} \textbf{Df} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0.4}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} \textbf{Pr($>$Chisq)} \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0.4}}r!{\huxvb{0, 0, 0}{0}}}{\cellcolor[RGB]{242, 242, 242}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 10 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\cellcolor[RGB]{242, 242, 242}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 4.57e+03 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\cellcolor[RGB]{242, 242, 242}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 4.62e+03 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\cellcolor[RGB]{242, 242, 242}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} -2.28e+03 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\cellcolor[RGB]{242, 242, 242}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 4.55e+03 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\cellcolor[RGB]{242, 242, 242}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} \hphantom{0}\hphantom{0}\hphantom{0} \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\cellcolor[RGB]{242, 242, 242}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt}  \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0.4}}}{\cellcolor[RGB]{242, 242, 242}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} \hphantom{0}\hphantom{0}\hphantom{0}\hphantom{0} \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.4}}|>{\huxb{0, 0, 0}{0.4}}|}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0.4}}r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 12 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 4.58e+03 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 4.63e+03 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} -2.28e+03 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 4.55e+03 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 1.51 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 2 \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0.4}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 0.471 \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}-}
\arrayrulecolor{black}
\end{tabular}
\end{threeparttable}\par\end{centerbox}

\end{table}
 

The ANOVA analysis shows that random slope model is not better than the
random intercept model.

\pandocbounded{\includegraphics[keepaspectratio]{BIOS-667-Group-Project_files/figure-latex/unnamed-chunk-17-1.pdf}}
Figure 6 illustrates the model-predicted trajectories for TWSTRS across
the three treatment groups. The blue line representing 10000 U treatment
and the red line for placebo cross each other, showing the significant
interaction term between 10000 U and week. The relationship between
treatment and score depends on time.

\pandocbounded{\includegraphics[keepaspectratio]{BIOS-667-Group-Project_files/figure-latex/unnamed-chunk-18-1.pdf}}

Figure 7 displays the observed TWSTRS scores (points) overlaying the
GLMM fitted trajectories (lines) for a random sample of 12 subjects. The
heterogeneity at baseline confirms the necessity of including a random
intercept for each subject to account for patient-specific
heterogeneity, suggesting that much of the variance arises from
pre-existing differences between patients.

The relationship between the solid lines and scattered points
demonstrates how the model generates Best Linear Unbiased Predictions
(BLUPs) for each subject. Instead of overfitting to the noisy
week-to-week fluctuations observed in the raw data points, the model
fits smooth linear trajectories that balance individual trends with the
overall population average.

\pandocbounded{\includegraphics[keepaspectratio]{BIOS-667-Group-Project_files/figure-latex/unnamed-chunk-19-1.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{BIOS-667-Group-Project_files/figure-latex/unnamed-chunk-19-2.pdf}}

\begin{verbatim}
## $opt
## [1] 0
## 
## $lme4
## list()
\end{verbatim}

The plot of Pearson residuals against fitted values (Figure 8) shows a
random scatter of points around the zero line without a distinct funnel
shape. This indicates that the assumption of constant variance
(homoscedasticity) is reasonably satisfied, and the linear mean
structure is adequate. The plot of residuals against time (Figure 9)
displays a slight non-linear trend. The dip suggests that the model is
overpredicting the TWSTRS scores around Weeks 4 and 5. However, the
residuals generally remain centered near zero, indicating the linear
approximation is adequate for the primary analysis.

The Q-Q plot for the random intercepts (Figure 10) assesses the
assumption that subject-specific deviations follow a normal
distribution. The points fall closely along the red diagonal reference
line, with only negligible deviations at the extreme tails. This
confirms that the assumption of normally distributed random effects is
well satisfied.

We also confirm that the model converged successfully.

\subsection{Discussion}\label{discussion}

Summarization of main points, conclusions based in results Summarization
of the various models applied, which ones you prefer and base your
interpretations off of and why Discussion of limitations if any

\subsection*{References}\label{references}
\addcontentsline{toc}{subsection}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-jankovic_treatment_2023}
Jankovic, J., Tsui, J., \& Brin, M. F. (2023). Treatment of cervical
dystonia with {Botox} ({Onabotulinumtoxina}): {Development}, insights,
and impact. \emph{Medicine}, \emph{102}(S1), e32403.
\url{https://doi.org/10.1097/MD.0000000000032403}

\bibitem[\citeproctext]{ref-wetmore_clinical_2025}
Wetmore, E., Roberts, H., Livinski, A. A., Camacho, T., Eaton, C.,
Norato, G., Hallett, M., \& Stacy, M. (2025). Clinical response to
placebo botulinum toxin injection in cervical dystonia---a systematic
review and meta-analysis. \emph{Dystonia}, \emph{4}, 14297.
\url{https://doi.org/10.3389/dyst.2025.14297}

\end{CSLReferences}

\end{document}
